name: docker-build-push
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip build')"
    runs-on: ubuntu-latest

    steps:
      - name: build
        uses: actions/checkout@v2
      
      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get the version number
        id: vars
        run: echo "{{ github.event.head_commit.id }}"
      - name: Build the image
        run: docker build -t tazimtaz/flask-rabbitmq:{{ github.event.head_commit.id }} .
      - name: Push the image
        run: docker push tazimtaz/flask-rabbitmq:{{ github.event.head_commit.id }}
      - name: Build the latest docker image
        run: docker build -t tazimtaz/flask-rabbitmq:latest .
      - name: Push the latest docker image
        run: docker push tazimtaz/flask-rabbitmq:latest
      
